apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-kanban.fullname" . }}
  labels:
    {{- include "simple-kanban.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "simple-kanban.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "simple-kanban.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "simple-kanban.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
            {{- if .Values.storage.postgres }}
            - name: POSTGRES_HOST
              value: {{ .Values.storage.postgres.hostname }}
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: {{ .Values.storage.postgres.database }}
            - name: POSTGRES_USER
              value: {{ .Values.storage.postgres.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.postgres.existingSecret }}
                  key: {{ .Values.storage.postgres.userPasswordKey }}
            {{- end }}
            {{- if .Values.cache.redis }}
            - name: REDIS_HOST
              value: {{ .Values.cache.redis.hostname }}
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.cache.redis.existingSecret }}
                  key: {{ .Values.cache.redis.passwordKey }}
            {{- end }}
          envFrom:
            {{- if or .Values.storage .Values.cache }}
            - configMapRef:
                name: {{ include "simple-kanban.fullname" . }}-storage
            {{- end }}
            {{- if .Values.configMap.data }}
            - configMapRef:
                name: {{ include "simple-kanban.fullname" . }}
            {{- end }}
            {{- if .Values.secret.data }}
            - secretRef:
                name: {{ include "simple-kanban.fullname" . }}
            {{- else }}
            - secretRef:
                name: {{ include "simple-kanban.fullname" . }}-app-secrets
            {{- end }}
            {{- if .Values.storage.postgres.existingSecret }}
            - secretRef:
                name: {{ .Values.storage.postgres.existingSecret }}
            {{- end }}
            {{- if .Values.cache.redis.existingSecret }}
            - secretRef:
                name: {{ .Values.cache.redis.existingSecret }}
            {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: var-cache
              mountPath: /var/cache
            - name: google-oauth-secret
              mountPath: /var/secrets/kanban
              readOnly: true
      volumes:
        - name: tmp
          emptyDir: {}
        - name: var-cache
          emptyDir: {}
        - name: google-oauth-secret
          secret:
            secretName: {{ .Values.oidc.googleOAuthSecret | default "google-oauth-json" }}
            optional: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
