{{- if .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-kanban.fullname" . }}
  labels:
    {{- include "simple-kanban.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if not .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simple-kanban.fullname" . }}-app-secrets
  labels:
    {{- include "simple-kanban.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  SESSION_SECRET_KEY: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
